project_id = "fxiymiaexmxvacnbyhrq"

[functions.stt]
verify_jwt = true

[functions.tts]
verify_jwt = true

[functions.precheck]
verify_jwt = true

[functions.generate]
verify_jwt = false

[functions.generate-pdf]
verify_jwt = true

[functions.stripe-webhook]
verify_jwt = false

[functions.create-checkout-session]
verify_jwt = true

[functions.customer-portal]
verify_jwt = true

[functions.meta-pixel-api]
verify_jwt = false